package com.group2.userservice.awsmicroservicegroup2.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

@Data
@DynamoDBTable(tableName = "user")
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class User {

    @DynamoDBHashKey(attributeName = "user_id")
    @DynamoDBAutoGeneratedKey
    private String user_id;

    @DynamoDBAttribute
    private String username;

    @DynamoDBAttribute
    private String email;

    @DynamoDBAttribute
    private String password_hashed;

    @DynamoDBAttribute
    private Date registration_date;

    @DynamoDBAttribute
    private Date last_login;

    @DynamoDBAttribute
    private boolean is_admin;
}
